wandb_version: 1

MAX_SEQUENCE_LENGTH:
  desc: null
  value: 64
PROCESSING_BATCH_SIZE:
  desc: null
  value: 512
INVERSION_BATCH_SIZE:
  desc: null
  value: 128
BASE_MODEL:
  desc: null
  value: bias-bios64
NUM_CORRECTION_STEPS:
  desc: null
  value: 20
BEAM_SEARCH_SIZE:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714058029.207781
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 75
      - 95
      - 100
      3:
      - 16
      - 23
      4: 3.11.7
      5: 0.16.2
      6: 4.35.0
      8:
      - 5
      13: linux-x86_64
